name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    strategy:
      matrix:
        go: [ '1.20.x', '1.21.x' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Deps
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2

    - name: Lint
      run: golangci-lint run --config .golangci.yml -v ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race -coverprofile coverage.txt ./...

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: coverage.txt
